mystatistics/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mystats_app/', include('mystats_app.urls')),
    
    
]

mystats_app/urls.py
from django.urls import path

from . import views

app_name = "mystats_app"
urlpatterns = [
    path('', views.index, name='index'),
    path('added/', views.added, name='added'),
    #angelegt und gehofft dass es funktioniert
]

mystats_app/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Action(models.Model):
    action_text = models.CharField(max_length = 200)
    entry_date = models.DateTimeField(default=datetime.now())
    
    def __str__(self):
            return self.action_text
    
    def entered(self):
        return self.entry_date
    

mystats_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from datetime import datetime

import csv
# Create your views here.
from .models import Action

def index(request):
    actions = Action.objects.all()
    return render(request, 'mystats_app/index.html', {'actions': actions})
    print(request)
    
#Angelegt, um zu versuchen auf zweite html zuzugreifen: 
def added(request):
    action = request.POST['action_name']
    date = datetime.now()
    Action.objects.create(action_text = action) #siehe models
    getfile(action, date)
    return render(request, 'mystats_app/new_action.html')
    
def getfile(action, date):  
    datei = open('daten1.csv', 'a')
    datei.write(action)
    datei.write(';')
    datei.write(str(date))
    datei.write('\n')
    datei.close()
    #with open('daten.csv', 'w') as f:
    #    writer = csv.writer(f,quotechar ='"', quoting=csv.QUOTE_MINIMAL)
    #    writer.writerow(action)

mystats_app/templates/mystats_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  <title>Statistics</title>

  
</head>
<body>
	<p>Dies ist meine Index-Ansicht</p>
	<form action="{% url "mystats_app:added" %}" method="post">
		{% csrf_token %}
		
		<label>Eintrag:</label>
		<input type="text" name="action_name">
	<br>
		{% for action in actions %}
			{{action.entry_date }} {{action.action_text}} <!-- for entry in liste: print entry -->
			<br>
		{% endfor %}
</body>
</html>

mystats_app/templates/mystats_app/new_action.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Neuer Eintrag gespeichert!</title>

  
</head>
<body>
	<p>Neue Aktion eingespeichert.</p>
</body>
</html>